backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Publish mode options:
# - editorial_workflow: Content goes through drafts -> review -> ready before publishing
# - simple: Content is published immediately
publish_mode: editorial_workflow

# Media folder where uploaded images will be stored
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Collections define the structure for content types
collections:
  - name: "content"
    label: "Website Content"
    files:
      - name: "home"
        label: "Home Page Content"
        file: "content/content.md"
        description: "Content for the SocialSpark website"
        fields:
          # Header Section
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - { label: "Logo", name: "logo", widget: "string" }
          
          # Navigation
          - label: "Navigation"
            name: "navigation"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
          
          # Hero Section
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "object"
                fields:
                  - { label: "Line 1", name: "line1", widget: "string" }
                  - { label: "Line 2", name: "line2", widget: "string" }
                  - { label: "Line 3", name: "line3", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Button"
                name: "button"
                widget: "object"
                fields:
                  - { label: "Text", name: "text", widget: "string" }
                  - { label: "URL", name: "url", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Sticker Text", name: "sticker", widget: "string" }
              - { label: "Polaroid Caption", name: "polaroidCaption", widget: "string" }
          
          # Services Section
          - label: "Services Section"
            name: "services"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - label: "Service Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Icon", name: "icon", widget: "string", hint: "Use emoji or icon code" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }
          
          # This & That Section
          - label: "This & That Section"
            name: "thisAndThat"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "First Term", name: "firstTerm", widget: "string" }
                  - { label: "Second Term", name: "secondTerm", widget: "string" }
          
          # Portfolio Section
          - label: "Portfolio Section"
            name: "portfolio"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - label: "Mockups"
                name: "mockups"
                widget: "list"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Caption", name: "caption", widget: "string" }
              - { label: "Grid Title", name: "gridTitle", widget: "string" }
              - label: "Portfolio Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Title", name: "title", widget: "string" }
          
          # Testimonial Section
          - label: "Testimonial Section"
            name: "testimonial"
            widget: "object"
            fields:
              - { label: "Quote", name: "quote", widget: "text" }
              - { label: "Author", name: "author", widget: "string" }
          
          # Stats Section
          - label: "Stats Section"
            name: "stats"
            widget: "object"
            fields:
              - label: "Stat Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Value", name: "value", widget: "string" }
                  - { label: "Label", name: "label", widget: "string" }
          
          # Contact Section
          - label: "Contact Section"
            name: "contact"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - label: "Contact Info"
                name: "info"
                widget: "list"
                fields:
                  - { label: "Icon", name: "icon", widget: "string", hint: "Use emoji or icon code" }
                  - { label: "Text", name: "text", widget: "string" }
              - label: "Form"
                name: "form"
                widget: "object"
                fields:
                  - { label: "Action URL", name: "action", widget: "string" }
          
          # Footer
          - label: "Footer"
            name: "footer"
            widget: "object"
            fields:
              - { label: "Logo", name: "logo", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Social Media"
                name: "social"
                widget: "object"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - label: "Social Icons"
                    name: "icons"
                    widget: "list"
                    fields:
                      - { label: "Type", name: "type", widget: "select", options: ["facebook", "instagram", "x", "youtube"] }
                      - { label: "URL", name: "url", widget: "string" }
              - { label: "Copyright", name: "copyright", widget: "string" }
          
          # Notification
          - label: "Notification"
            name: "notification"
            widget: "object"
            fields:
              - { label: "Message", name: "message", widget: "string" }
